
---
name: build and publish docker images

on:
  push:
    branch:
      - 'main'
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        ros_distro: ['galactic', 'humble', 'rolling']
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ros:${{ matrix.ros_distro }}-rhel
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}